### ISSUE TITLE
Need some tests

### ISSUE THREAD

**Issue by bleonard** [queue-bus/sidekiq-bus#1]
@jonsgreen I added the base level tests to this project.
I've set it up so all the tests in the spec folder of queue-bus can be copied into the child projects.
Then adapter-specific tests should go in the `spec/adapter/` directory

For example in the resque project, it does a full integration test actually running the resque workers.

Check out that project for examples.
https://github.com/queue-bus/resque-bus/tree/master/spec/adapter

Are you up for adding those and testing this gem in your environment?

**Comment by jonsgreen** [comment]
@bleonard: I apologize for not having gotten back to you. Some time sensitive things came up at work and I have not gotten back to this; and I was the one bugging you to make this all happen!

Anyhow. I will try to look into making something happen in the next 24 hours or at least report back on my progress if I am unable to get to it. 

Thanks again for all that you have done setting this up.

**Comment by bleonard** [comment]
No major rush. Just making sure you are up to date on the changes in the last few days.

**Comment by jonsgreen** [comment]
@bleonard I have finally adapted the Resque integration specs for Sidekiq: https://github.com/queue-bus/sidekiq-bus/pull/2. You will see that I also added a few conveniences that may or may not be to your liking. Although Mike Perham discouraged me from using it I have found fakeredis to be an easy way to get around needing to have Redis running. I was actually finding that some specs would fail if I was using redis on a different project at the same time. 

You will see that there are various ways to test Sidekiq integration. I included two variations of the first spec one using Sidekiq::Testing.fake! the other Sidekiq::Testing.inline!. The first copies the structure of the ResqueBus spec though it is neat that when run inline everything moves through the Driver and Rider workers in one go. 

The other two 'Delayed Publishing' specs feel a but dirty since I ended up using some lower level Sidekiq in order to mimic the Resque specs. Perhaps they are not even necessary since they end up really testing Sidekiq more. Nevertheless it is reassuring to see them green. 

I guess the other thing that still needs doing is adapting the rake tasks for Sidekiq. In my earlier pull request: https://github.com/taskrabbit/resque-bus/pull/14/files#diff-2f4e7a0f983ba2cd9418a2992613ff2dL26 I just added some output since there does not seem to be a similar way to add queues through an environment variable: https://github.com/mperham/sidekiq/issues/2086#issuecomment-69844292. We could ask Mike Perham to see if he has any other suggestions about this or the adapter in general. 

Last week I was quite busy getting the old ResqueBus integrated with our project in our staging environment.   I thought I would get that working first and maybe at some point this week I can try this gem out locally and report back what I find. 

Thanks for your patience and let me know if there is any other way that I can help out and

**Comment by bleonard** [comment]
one thing to note if you are integrating the old `resque-bus` in will be a transition problem between that version and `sidekiq-bus` -- the class names in the queue will be `ResqueBus::Driver` and the like. In the new version, it will be `QueueBus::Worker` -- this will cause you queues to crash.
In the new `resque-bus`, I was going to make that transition seamless (by re-including those classes in the _new_ version).

All of which to say, that if you could go right for `sidekiq-bus`, it will be easier.

**Comment by bleonard** [comment]
another note: I wouldn't say it's the biggest deal in the world about the rake jobs. we don't even use them in production for resquebus now. we just know the queue names and rock them in our deploy scripts.
